buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ":"
responseHeaders:
- 
  pathPattern: .*
  headerKey: Access-Control-Allow-Origin
  headerValues:
    - "*"
