buildConfiguration:
  buildCommand: npx pages build --scope myScope
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ":"
assetsDir: subdirectory/assets
# The ^modules/ header allows access to your modules from other sites
responseHeaders:
  - pathPattern: ^modules/myScope/test.*
    headerKey: Access-Control-Allow-Origin
    headerValues:
      - "*"
